title: "好看韩剧"
name: hanjutv
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  bitsdojo_window: ^0.1.5
  http: ^1.3.0
  html: ^0.15.5
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.1.0
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

msix_config:
  display_name: "好看韩剧"
  publisher_display_name: 杨再涛
  identity_name: company.suite.hanjutv
  msix_version: 1.0.0.0
  logo_path: C:\Users\limin\Desktop\icon.png
  capabilities: internetClient, location, microphone
  certificate_path: C:\Users\limin\Desktop\zs\HKHJ.pfx
  certificate_password: password